### ISSUE TITLE
Which license is all this scripts under?

### ISSUE THREAD

**Issue by SuddenGunter** [dave-burke/ansible-playbook#1]
I want to reuse it in my MIT-licensed repo, can I do this?

**Comment by dave-burke** [comment]
Hi! Thanks for asking about this. Sorry I didn't reply earlier. The notification must have gotten lost in my email inbox and I just noticed your issue now. I believe in strong copyleft provisions, so I added a license of GPLv3. Unfortunately I do not think that can be used in an MIT licensed project.
